"""
ai/models/agent_decision.py
"""

from __future__ import annotations

import logging
from enum import Enum
from typing import Any
from pydantic import BaseModel, ConfigDict, Field, field_validator


# Global -------------------------------------------------------------------- #


logger = logging.getLogger(__name__)


# Classes ------------------------------------------------------------------- #


class AgentAction(str, Enum):
    """High-level actions requested by the agent."""

    IDLE = "idle"
    PICK = "pick"
    INSPECT = "inspect"
    CANCEL = "cancel"
    EMERGENCY_STOP = "emergency_stop"


class AgentDecision(BaseModel):
    """Structured output generated by the MainAgent."""

    model_config = ConfigDict(extra="forbid")

    action: AgentAction = Field(..., description="Requested robot action.")
    target_object: str | None = Field(
        default=None,
        description="Target object for manipulation or inspection.",
    )
    message: str | None = Field(
        default=None,
        description="Human-readable response for the operator.",
    )
    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Decision confidence in the [0.0, 1.0] range.",
    )
    requires_confirmation: bool = Field(
        default=False,
        description="Whether operator confirmation is required.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Optional extra structured context.",
    )

    @field_validator("target_object")
    @classmethod
    def _normalize_target_object(cls, value: str | None) -> str | None:
        """Normalize target object strings."""

        if value is None:
            return None

        normalized = value.strip()
        return normalized or None
